Homework 9
kdr1mkf/IgorShabanov-RestAssured pull request #1
Opened 2021-09-13 18:24 UTC by kdr1mkf

Homework seem to be done.

2021-09-15 07:02 UTC, GrebNat approved these changes
All comments should be applied to similar issues in different classes

2021-09-15 07:02 UTC, GrebNat commented on src/test/java/test/CommonTest.java
> +    protected void makeEntityNameUnique(CommonEntity entity, String nameToBeCompared) {
move it out from test lays to data generation/creation layer

2021-09-15 07:04 UTC, GrebNat requested changes
pls, follow comments

2021-09-15 07:27 UTC, kdr1mkf commented on src/main/java/constant/ActionEndpoint.java
> +public class ActionEndpoint {
Fixed,

2021-09-15 07:38 UTC, kdr1mkf commented on src/main/java/constant/Endpoint.java
> +    public static final String BASE = "https://api.trello.com/1";
Fixed.

2021-09-15 07:43 UTC, kdr1mkf commented on src/main/java/domain/Board.java
> +    @SerializedName("id")
Fixed.

2021-09-15 09:56 UTC, kdr1mkf commented on src/main/java/domain/Board.java
> +    public Board() {
BoardFactory, ListFactory implemented.

2021-09-15 10:40 UTC, kdr1mkf commented on src/test/java/test/CommonTest.java
> +    protected void makeEntityNameUnique(CommonEntity entity, String nameToBeCompared) {
Fixed.

2021-09-16 08:41 UTC, kdr1mkf commented on src/main/java/service/BoardService.java
> +            .then()
Status code assertion moved to CommonRequest class.

2021-09-16 08:42 UTC, kdr1mkf commented on src/main/java/service/BoardService.java
> +            .and()
Fixed.

2021-09-16 08:44 UTC, kdr1mkf commented on src/main/java/service/BoardService.java
> +        createdBoards.remove(board);
Created entities collections are moved to a separate class. Add and delete an entity methods are invoked by test classes.

2021-09-16 08:45 UTC, kdr1mkf commented on src/main/java/service/BoardService.java
> +        List<Board> boardsToDelete = new ArrayList<>(createdBoards);
Created entities collections are moved to a separate class.

2021-09-16 17:11 UTC, kdr1mkf commented on src/main/java/domain/Board.java
> +    public String getId() {
Lombok @Getter and @Setter annotations applied.

2021-09-17 09:16 UTC, GrebNat requested changes

2021-09-17 09:16 UTC, GrebNat commented on src/main/java/service/BoardService.java
> +        return new BoardRequest(Endpoint.BASE, Method.DELETE)
Endpoint.BASE move it to common level

2021-09-17 09:16 UTC, GrebNat commented on src/test/java/assertions/StaticAssertions.java
> +package assertions;
move asserts to src/main/java

2021-09-17 09:16 UTC, GrebNat commented on src/test/java/assertions/StaticAssertions.java
> +        Assertions.assertThatThrownBy(shouldRaiseThrowable)
request fail means, that status code is 400. try to check status code

2021-09-17 09:16 UTC, GrebNat commented on src/test/java/test/BoardTest.java
> +        Board expectedBoard = BoardFactory.getDefaultBoard();
will be smarter
Board expectedBoard = BoardFactory.getDefaultBoard(boardName)

2021-09-17 09:16 UTC, GrebNat commented on src/test/java/test/BoardTest.java
> +        assertRequestFailed(() -> createBoard(expectedBoard));
see comments about assertRequestFailed

2021-09-17 09:16 UTC, GrebNat commented on src/test/java/test/CommonTest.java
> +        PropertiesHandler secretProperties = new PropertiesHandler(".\\src\\test\\resources\\secret.properties");
.\\src\\test\\resources\\secret.properties

property path should be handled by  TrelloProperty class

2021-09-17 09:16 UTC, GrebNat commented on src/test/java/test/CommonTest.java
> +        PropertiesHandler testProperties = new PropertiesHandler(".\\src\\test\\resources\\test.properties");
same as above

2021-09-17 09:16 UTC, GrebNat commented on src/test/java/test/CommonTest.java
> +    protected Board updateBoardName(Board boardToRename, String newName) {
this method is no need, as board is deleted by ID, name or another field changing should not affect deleting

2021-09-17 09:16 UTC, GrebNat commented on src/test/java/test/CommonTest.java
> +    protected Response deleteBoard(Board boardToDelete) {
no need

2021-09-17 09:16 UTC, GrebNat commented on src/test/java/test/CommonTest.java
> +        Set<Board> allCreatedBoards = EntitiesKeeper.getAllCreatedBoards();
move to BoardService like deleteAllCreatedBoards(BoardDTO ... boardsToDelete){} or
deleteAllCreatedBoards(String ... boardsToDeleteIDs){}

2021-09-17 09:16 UTC, GrebNat commented on src/test/resources/test.properties
> +base_url = https://api.trello.com/1
add secrets

2021-09-17 16:02 UTC, kdr1mkf commented on src/main/java/domain/Board.java
> +    @Override
I would rather override hashcode and equals on my own. Data annotation overrides hascode and equals methods based on all class fialds. I don't want those methods been based on all of the fields.

2021-09-17 17:18 UTC, kdr1mkf commented on src/test/java/assertions/StaticAssertions.java
> +package assertions;
Fixed

2021-09-17 17:45 UTC, kdr1mkf commented on src/main/java/service/BoardService.java
> +            .setName(boardToCreate.getName())
Request parameters are set by body (entities).

2021-09-17 17:59 UTC, kdr1mkf commented on src/main/java/service/BoardService.java
> +        return new BoardRequest(Endpoint.BASE, Method.DELETE)
Setting request base url moved to the CommonRequest class.

2021-09-17 17:59 UTC, kdr1mkf commented on src/test/java/assertions/StaticAssertions.java
> +        Assertions.assertThatThrownBy(shouldRaiseThrowable)
I'm not able to check it since status code 200 is checked at the request level. Asserting status code 400 requires providing Response objects to the test layer. Test layer has already got complicated. I'd say, too much complicated. Entities seem to be useless then.

2021-09-17 18:04 UTC, kdr1mkf commented on src/test/java/test/BoardTest.java
> +        Board expectedBoard = BoardFactory.getDefaultBoard();
I suppose getting a default board shouldn't require any arguments. The factory is supposed to take care about everything a board needs to be valid. I don't see no reasons to make getBoardWithCustomName methods since Board setters are implemented.

2021-09-17 18:35 UTC, kdr1mkf commented on src/test/java/test/CommonTest.java
> +        Set<Board> allCreatedBoards = EntitiesKeeper.getAllCreatedBoards();
BoardService.deleteBoards(Collection<Board>) implemented.

I don't think that's a good dicision since createdBoards and createdLists must be cleared. Handling createdEntities lists was moved to test layer on purpose (first try comments). So moving lists clearing back to the service layer seems to be weird.

2021-09-17 18:40 UTC, kdr1mkf commented on src/test/java/test/CommonTest.java
> +    protected Response deleteBoard(Board boardToDelete) {
Why? Tests got so complicated that I barely fixed them according to previous comments. This method extracts actions on board deleting and nmakes test a bit more clear.

2021-09-17 19:10 UTC, kdr1mkf commented on src/test/java/test/CommonTest.java
> +        PropertiesHandler secretProperties = new PropertiesHandler(".\\src\\test\\resources\\secret.properties");
Fixed.

2021-09-17 19:16 UTC, kdr1mkf commented on src/test/java/test/CommonTest.java
> +        PropertiesHandler testProperties = new PropertiesHandler(".\\src\\test\\resources\\test.properties");
Fixed.

2021-09-17 19:37 UTC, kdr1mkf commented on src/test/resources/test.properties
> +base_url = https://api.trello.com/1
Fixed.

2021-09-17 19:50 UTC, kdr1mkf commented on src/main/java/constant/Endpoint.java
> +    public static String BASE = "";
I believe constants make the code easier to read. Invoking TrelloProperty().getBaseURL() seems to me more complicated than my approach.

That fix requires the other constants to be converted into getters too.

2021-09-17 19:51 UTC, kdr1mkf commented on src/main/java/constant/Secret.java
> +    public static String KEY;
It's stored in property file. I don't get the message.

2021-09-17 19:52 UTC, kdr1mkf commented on src/main/java/domain/CommonEntity.java
> +    String getName();
I need the interface to handle all the entities the same way.

I suppose I don't get the message again.

2021-09-17 19:53 UTC, kdr1mkf commented on src/main/java/factory/CommonEntityFactory.java
> +    public static void makeEntityNameUnique(CommonEntity entity, String nameToBeCompared) {
I would rather generate a name by date stamp but I see no reasons to make the approach complicated. It works as is.

2021-09-17 20:07 UTC, kdr1mkf commented on src/main/java/request/CommonRequest.java
> +            .addQueryParam(Secret.KEY_PARAMETER_NAME, Secret.KEY)
I wouldn't rather mix credentials and other properties.

2021-09-17 20:09 UTC, kdr1mkf commented on src/test/java/test/CommonTest.java
> +    protected Board updateBoardName(Board boardToRename, String newName) {
I don't get the message. This method has nothing to do with deleting.

2021-09-20 11:25 UTC, GrebNat commented on src/test/java/test/BoardTest.java
> +        Board expectedBoard = BoardFactory.getDefaultBoard();
it is up to u, but overloading getDefaultBoard will be smarter

2021-09-21 15:59 UTC, kdr1mkf commented on src/main/java/constant/Endpoint.java
> +    public static String BASE = "";
All properties are moved to the Properties class.

2021-09-22 07:37 UTC, GrebNat approved these changes

2021-09-22 16:58 UTC, merged